import { wrapper } from '@/app/store'
import { getBaseLayout } from '@/layouts/publ/BaseLayout/BaseLayout'
import { getRunningQueriesThunk } from '@/services/api/api'
import { getAllPosts, getTotalCount } from '@/services/publicService/publicEndpoints'
import { PublicPosts } from '@/widgets/root/publicPosts'
import { GetStaticPropsResult } from 'next'
import Head from 'next/head'

type Props = {
  isPostsError?: boolean
  isUsersError?: boolean
}

export const getStaticProps = wrapper.getStaticProps(
  store => async (): Promise<GetStaticPropsResult<Props>> => {
    const users = await store.dispatch(getTotalCount.initiate(undefined, { forceRefetch: true }))
    const posts = await store.dispatch(getAllPosts.initiate({}, { forceRefetch: true }))

    await Promise.all(store.dispatch(getRunningQueriesThunk()))

    if (!posts) {
      return {
        props: {
          isPostsError: true,
        },
        revalidate: 60,
      }
    }

    if (!users) {
      return {
        props: {
          isUsersError: true,
        },
        revalidate: 60,
      }
    }

    return {
      props: {},
      revalidate: 60,
    }
  }
)

const HomePage = () => {
  return (
    <>
      <Head>
        <title>InstaLife</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <main style={{ width: '100%' }}>
        <PublicPosts.widget />
      </main>
    </>
  )
}

HomePage.getLayout = getBaseLayout
export default HomePage
